# version: "3.9"

# services:
#   fastapi:
#     image: teeworksacr.azurecr.io/fastapi-service:latest
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./app:/app
#     environment:
#       - PYTHONUNBUFFERED=1

services:
  fastapi:
    image: teeworksacr.azurecr.io/fastapi-service:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
  web:
    image: teeworksacr.azurecr.io/test-api:latest
    ports:
        - "8200:8200"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8200"]